### ISSUE TITLE
Should the response data include an "expires" field?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-methods-tokenization#12]
In addition to the proposed oneTimeUse field, should the response data include metadata about expiration of the token? Or is this information typically part of the token itself? Or otherwise determined (e.g., server-side communication)?

Ian

**Comment by mattsaxon** [comment]
I propose it is optional and applicable to both multi use and single use tokens

**Comment by oyiptong** [comment]
i'm in support for this

**Comment by oyiptong** [comment]
the expires field is nice to have, however, it should not be viewed as an authoritative source of information.

There are many reasons why the token might get expired and the most direct way to know is when a charge is requested.

The tokenization provider will respond with a success or a failure. The failure generally contains an error code which explains why the token is rejected. some of those errors may lead the merchant to evict the token, perhaps ahead of a suggested expiry time.

**Comment by ianbjacobs** [comment]
I suggest we close this issue in favor of https://github.com/w3c/webpayments-methods-tokenization/issues/25
