### ISSUE TITLE
Structuring the tokenization payment method(s)

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-methods-tokenization#13]
In this issue I'd like to hear different viewpoints on whether:

* We should have two (or more) payment methods related to (1) gateway tokens and
   (2) network tokens, or try to create one. 

* Depending on that outcome, whether we should define multiple payment methods in
  a single specification or multiple specifications.

We discussed this a bit at the 18 July call:
 https://www.w3.org/2017/07/18-wpwg-minutes#item01

**Comment by mattsaxon** [comment]
I think it is too early to say if we should have one or two or in fact many. on the many point, I could see an approach where we standardise a set of base data, but allow an arbitrary PMI to use the data.

This has a couple of benefits;

1. We can dispense with the tokenProviderURL param, instead using the PMI (which is a URL)
2. Providers can extend the base data to allow for innovation in the ecosystem

**Comment by ianbjacobs** [comment]
Closing this issue for now and will deal with the question as we make progress.
