### ISSUE TITLE
Linkage to BasicCard Spec

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments-methods-tokenization#17]
The [gateway_params](https://github.com/w3c/webpayments-methods-tokenization/wiki/gateway_params#data-sent-to-tokenization-provider) article provides info that relates to basic-card. This should be referenced and we should not duplicate definitions such as CardData dictionary.

**Comment by ianbjacobs** [comment]
This was also raised in #26. However, note disagreement on whether the tokenization spec should reference Basic Card or not:
 https://github.com/w3c/webpayments-methods-tokenization/issues/26#issuecomment-359195146
 https://github.com/w3c/webpayments-methods-tokenization/issues/26#issuecomment-359309645

**Comment by ianbjacobs** [comment]
Closing this issue since, in practice, we are both bringing in some pieces of basic card (in WebIDL) and referring to other parts of basic card (for some definitions). As the spec matures, we might move in the direction of further independence.
