### ISSUE TITLE
Split up card-token payment method into multiple types

### ISSUE THREAD

**Issue by oyiptong** [w3c/webpayments-methods-tokenization#2]
Let's split up the `card-token` payment method into multiple types.

I propose:

* gateway-tokenized-card
* emv-tokenized-card
* ... ?

**Comment by ianbjacobs** [comment]
Hi @oyiptong,

Can we translate the suggestion into text-level changes to the draft?
 https://w3c.github.io/webpayments/proposals/tokenized_cards.html

For example, are you proposing values for the "supportedTokenTypes" field?
(If so, we have "emv" already and we should keep them short.)

Ian

**Comment by oyiptong** [comment]
I guess I was trying to spark a discussion more than proposing things.

We last talked about splitting `card-token` into more specialized types because the parameters the different tokenization strategies might be different.

**Comment by oyiptong** [comment]
given the conversation at the teleconference today, i'll close this issue while we articulate what the scope of the spec should be
