### ISSUE TITLE
Multiuse flow

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments-methods-tokenization#20]
It is stated that in gateway-params that

// In multi-use scenarios, the token is not returned to merchant after the first transaction

This suggests that the merchant should have saved this, however why do we require that, I think it is feasible that the payment handler returns the same token on each call.

**Comment by MasterKeyur** [comment]
Is this for recurring payments like installments? Then it is possible using the same token returned in original token.

**Comment by ianbjacobs** [comment]
I am closing this issue since the current Tokenized Card Specification is now dealing with this question implicitly (and the wiki that this issue quotes was just for initial discussion).

Ian
