### ISSUE TITLE
What to do if tokenized data looks like basic card data?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-methods-tokenization#21]
Moving this out of the wiki to an issue to discuss at the right time:

When a tokenization scheme (such as network tokenization) results in data that looks just like Basic Card data (e.g., dynamic CVV or dynamic expiry, format of the token = format of a card number), should a payment app that provides this sort of data label it Basic Card? Or is there a need for an additional signal to the merchant or their PSP?

**Comment by MasterKeyur** [comment]
As part of current specification there is no dynamic CVV or expiry. There is cryptogram which the acquirer needs to send in authorization to Network (to issuer) along with token (16 -19 digit) and expiry of token. As of now there is no need of separate label.

**Comment by ianbjacobs** [comment]
I am going to close this issue because the way that the specification is going suggests the response data will not look like Basic Card.
