### ISSUE TITLE
Tokenized Card Spec Review

### ISSUE THREAD

**Issue by sachinahuja** [w3c/webpayments-methods-tokenization#24]
Please review the changes made as per our call on 28NOV2017 and comment here if anything is missing.

**Comment by ianbjacobs** [comment]
@sachinahuja,

Thanks for the edits. I have done an editorial pass and also reviewed it with respect to the 28 November discussion [1]. Let's discuss on 9 January.

Ian

[1] https://www.w3.org/2017/11/28-wpwg-minutes#item01

**Comment by ianbjacobs** [comment]
We have started to get review from Mozilla and Stripe as well; so I am going to close this issue for now.
