### ISSUE TITLE
Token properties?

### ISSUE THREAD

**Issue by asolove-stripe** [w3c/webpayments-methods-tokenization#25]
In reading the [current draft version](https://github.com/w3c/webpayments-methods-tokenization/wiki/Tokenized-Card), I notice that there are no constraints or communication flows about the properties of the returned payment token.

There are several ways that network tokens representing a card can differ:
- one time use v recurring use
- authorized only for specific amount v variable amounts
- chargeable only immediately or for any period of time in the future
- attached to a specific merchant or transaction type, etc.

Many business models require more than a simple one-time-use, fixed-amount token. A hotel will want to pre-authorize for the room total, but later be able to charge extra for your room service meal. A SaaS provider doesn't want to re-collect your billing information every month, even if your usage of the product changes the amount billed. (And yes, there is a complex set of regulatory and industry rules about this, but they currently support these use-cases in much of the world.)

Having the spec say nothing about the returned token seems like a problem. The worst case is that a merchant integrates against this method by testing with a few payment apps, only to discover that different apps implement the same method and return tokens with radically different properties. They may end up having to tear out PRAPI integration since they can't control different payment apps returning different kinds of tokens for the same payment method.

To avoid this, it seems like there are two options:
1. Revise the spec to add in tokenization options or an extra communication path so the merchant/PSP can communicate information to the TSP.
2. Explicitly specify that returned tokens MUST have a very minimal utility: one-time use, for the specified total, etc. While this is less powerful and solves fewer use cases, it at least avoids semantic differences between apps implementing the spec.

**Comment by adrianhopebailie** [comment]
I would favor option 1a (tokenization options) as this seems most flexible however would require some work to define the "options" that can be presented.

Are these a well-known set? Are they defined in the 3DS2 standard?

**Comment by stpeter** [comment]
We might want to use something like the `scope` parameter in OAuth 2.0: https://tools.ietf.org/html/rfc6749#section-3.3 (semantically, not syntactically).

See also: https://www.oauth.com/oauth2-servers/scope/defining-scopes/

**Comment by ianbjacobs** [comment]
Discussed on 30 January [1]. @MasterKeyur will begin to flesh out parameters for request data to help with canMakePayment() matching.

[1] https://www.w3.org/2018/01/30-wpwg-minutes#issue25

**Comment by clintonrallen** [comment]
Much of what is proposed would be reflected in the token domain restriction controls that are bound to the Token Requestor ID. 
The proposed information would then be communicated to the TSP in one of two ways. 

1. Merchant as the Token Requestor registers with the TSP outside of W3C Tokenisation resulting in a TRID unique to that merchant for each TSP representing specific payment token requirements. this would require including a TRID field on the request. 

2. Merchant provides this information in the W3C interfaces to a Token Requestor who has previously registered with each TSP. The TR using their TRID requests the payment token at a transactional level relaying the payment token request parameters to the TSP resulting in the issuance of a payment token for a specific use. 

In the  EMV® Payment Tokenisation Specification the parameters to consider may be found as distinctions between Cardholder initiated transactions and Merchant initiated Transactions.  Transaction types may be found in section 6 of EMV® Best Practices Document - Recommendations for EMV Processing for
Industry-Specific Transaction Types.
https://www.emvco.com/terms-of-use/?u=wp-content/uploads/documents/Recommendations-for-EMV-Processing-for-Industry-Specific-Transaction-Type.pdf

**Comment by ianbjacobs** [comment]
Hi all,
We had some discussion on this issue today:
 https://www.w3.org/2018/03/20-wpwg-minutes

**Comment by ianbjacobs** [comment]
Hello all,

Based on discussion in Singapore [1] I believe we provided a tentative answer to this issue, namely:

 * We want to enable both guest checkout and card-on-file use cases, and there should be a request field to allow the merchant to indicate which is desired.
 * There was a request for merchant id information to constrain tokens to that merchant/payee.

I am updating the spec accordingly and, if the task force is satisfied, I suggest we close this issue.

Ian

[1] https://www.w3.org/2018/04/20-wpwg-minutes#item01

**Comment by ianbjacobs** [comment]
Update:
 https://lists.w3.org/Archives/Public/public-payments-wg/2018May/0006.html

**Comment by ianbjacobs** [comment]
Good question from Giulio:
 https://lists.w3.org/Archives/Public/public-payments-wg/2018May/0023.html

**Comment by ianbjacobs** [comment]
At the 29 May meeting there was discussion about use cases where different parties might be able to provide a token in a given transaction, and the token might have different properties (e.g., domain controls). The example given was an issuing bank token or a card scheme token. The question arose whether the merchant might want to express a preference for the token it wanted. Although it was not discussed in depth, one idea for enabling merchants to express a preference for a token might be through the tokenUsageType, enabling the merchant to specify a preference order rather than a single type.

[1] https://www.w3.org/2018/05/29-wpwg-minutes.html#item03

**Comment by ianbjacobs** [comment]
I am closing this issue for now given discussion in Singapore and subsequently. I believe we have a fairly stable model and we will add new data based on more specific issues.
