### ISSUE TITLE
Drop the word 'card' from this payment method

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-methods-tokenization#27]
As discussed at the F2F I don't see the value in calling this tokenized **card**.

Physical cards are a legacy that will soon disappear from online payments. My hope is that this payment method will be around MUCH longer and will continue to be used even when the token is generated by a digital wallet that has no concept of a "card".

Concretely I propose:

1. The payment method identifier should be: `token`
2. Change `TokenizedCardRequest` to `TokenRequest`
3. Change `TokenizedCardResponse` to `TokenResponse`
4. Change `cardholderName` to `payerName`
5. Change `lastFourOfFPAN` to `paymentInstrumentLabel`
6. Change `card` to `payment instrument` or `account` in flow diagram.

I am happy to submit a PR if there is agreement on this proposal.

**Comment by ianbjacobs** [comment]
Hi @adrianhopebailie,

I recall the proposal from the face-to-face discussion. Whereas I don't have strong objections to the proposal, I would like to have a better understanding of other use cases than tokenized cards. Can you give some examples? Thanks!

Ian

**Comment by adrianhopebailie** [comment]
Almost all online payments in future are likely to be candidates. A 3DS 2.0 token is not just a representation of a PAN it is a representation of a complete authorization context.

It is not a "tokenised card" it is a "tokenised payment authorisation".

**Comment by ianbjacobs** [comment]
@adrianhopebailie, we discussed at the 30 January call [1]. Several people voiced the sense that this spec is very card specific. We will await your updated review before rediscussing.

Ian

[1] https://www.w3.org/2018/01/30-wpwg-minutes#item01

**Comment by ianbjacobs** [comment]
Given subsequent discussion that makes clear this specification is about card tokenization, I am closing this issue with no change. We can reopen if we find later that we have a non-card tokenization specification and want to merge them.
Ian

**Comment by adrianhopebailie** [comment]
I agree that the current work is about card tokenization so I suggest we be more explicit about this in other documents.

It seems strange to me that we have a body of work called "tokenization" but limit that to card tokenization.

**Comment by ianbjacobs** [comment]
Hi @adrianhopebailie,

What changes would you like to see in what documents?

Ian

**Comment by adrianhopebailie** [comment]
Change the name of the task force to "Card tokenization task force".
Change the name of this repo to "Webpayments card tokenization".

**Comment by ianbjacobs** [comment]
Hi @adrianhopebailie,

I have begun to rename the task force in our resources to "Tokenized Card Task Force".

As far as renaming the repo, I propose to wait until the time we get to FPWD. I think we are likely to want to rename the repo anyway (e.g., to "payment-method-tokenized-card" to follow the repo name for basic card).

Ian
