### ISSUE TITLE
Difference between "issuer token" ans "gateway token"

### ISSUE THREAD

**Issue by nelsonlyra** [w3c/webpayments-methods-tokenization#3]
Hi all,

What is the difference between "issuer token" ans "gateway token" ?

> "issuer": With these tokens, a provider serves as a card issuer by generating a new card number.

Does it means, that this token can only have this format : XXXX XXXX XXXX XXXX or a simple string can be used ?

> There are other types of tokens such as gateway tokens, but because they involve substantially different flows of information (e.g., merchant onboarding), this specification does not cover them

When dealing with tokenization, i'm quite sure that token services require some kind of onboarding/enrollment .. does it make sence to split all these custom tokens ? having only one "issuer token" with some metadata should'nt be more easy to use..?

Only some thougth about tokenization..
Nelson

**Comment by ianbjacobs** [comment]
Hi @nelsonlyra,

At today's call the task force started with the question of what problem we are trying to solve. Part of getting to an answer will involve a closer look at the use cases, token types, and flows, as you have started to do here.

It's not clear to me that we need to have an open issue on this. I think as our conversations proceed, we'll document the use cases and value proposition of work by the task force.

Would you be ok if we close this issue and reopen a more specific one further down the road?

Ian

**Comment by nelsonlyra** [comment]
Of course @ianbjacobs 
No problem for me.
