### ISSUE TITLE
Relationship between TokenizedCard and EncryptedTokenizedCard needs clarification

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-methods-tokenization#35]
Creating an individual issue from the list in #26 in reference to:
  https://github.com/w3c/webpayments-methods-tokenization/wiki/Tokenized-Card

"The relationship between TokenizedCard and EncryptedTokenizedCard is not clear (probably because currently we're punting on the encryption methods). At least this should be called out. More specifically, we should more carefully define the various fields (especially cryptogram, typeOfCryptogram, eci, trid), describe why each one needs to be included as input to the encryption operation (at least that's what they seem to be, but it's unspecified), describe which ones are required and which ones are optional, etc."

**Comment by adrianhopebailie** [comment]
I think there is a misunderstanding here.

The cryptogram, typeOfCryptogram, eci, trid etc are not related to the encryption of that data under the key specified with keyProviderUrl.

Those data elements are passed opaquely to the issuer where as the key from keyProviderUrl is used to encrypt this data between the payment handler and the merchant.

**Comment by ianbjacobs** [comment]
@adrianhopebailie I think you are correct. I have added a clarifying sentence to the spec and am closing this issue.
