### ISSUE TITLE
What are the supportedCryptogramTypes?

### ISSUE THREAD

**Issue by rvm4** [w3c/webpayments-methods-tokenization#47]
It looks like the spec has changed since I took down notes to create this issue, but it originally mentioned "UCAF" and the linked EMVCO document is huge. Is it possible to enumerate the possible values or have a more targeted reference?

**Comment by tricky456** [comment]
The UCAF/ 3DS style cryptogram is one potential version of a token cryptogram. 

EMVco define token cryptograms as implementation specific and can be variable length. 
 
As most networks are restricted by ISO 8583 standards, only certain fields are available to carry the cryptogram depending on the transaction type.  This also depends on what fields the merchant is certified to send information within.

UCAF/ 3DS style cryptogram is the most common for e-commerce transactions, but there is an option to provide other output data types to help restrict the domain and the use of that token.  

One example is a dynamic Security Code or Token verification value which is a 3/ 4 digit code which replaces the Card Security Code/ CVV on the back of a plastic card.

**Comment by ianbjacobs** [comment]
@rvm4 and @tricky456,

We discussed this issue today at the tokenization task force call. It was observed that the primary use case was going to involve "full cryptograms" and that each network would have (in practice) its own cryptogram format. Thus, indicating support for a network (through supportedNetworks) was sufficient and supportedCryptogramTypes could be removed. I have a pull request to do so (#49).

However, the people on the call also recommended that I seek additional input on this pull request, notably from merchants.

I welcome your thoughts on taking this approach.

Ian

**Comment by ianbjacobs** [comment]
I have begun to hear back from people a preference that the approach taken by the pull request (#49) to tie cryptogram types to network-supported types should work.

I hear some agreement to focus on "full cryptograms". I also note that dynamic CVV can be used with Basic Card.

**Comment by ianbjacobs** [comment]
Closed by merging pull request #49
