### ISSUE TITLE
How are empty supported* fields to be interpreted? 

### ISSUE THREAD

**Issue by rvm4** [w3c/webpayments-methods-tokenization#48]
I suspect the answer is that they should be interpreted as not supporting any, but I can see a small argument for them meaning that all are supported since the field is also optional.

**Comment by ianbjacobs** [comment]
Hi @rvm4,

As mentioned on today's call, part of the answer lies in the algorithms of the spec. See, for example: 

8.2 Steps to check if an instrument is supported 
https://w3c.github.io/webpayments-methods-tokenization/index.html#steps-to-check-if-an-instrument-is-supported

I adapted that text from Basic Card, but it has not been well-reviewed and may need work. 

It currently says:
  If types is empty and networks is empty, return true. 

It might need to say:
  If types is empty and networks is empty and cryptograms is empty, return true. 

I am inclined to make that change (for consistency with types and networks). Comments welcome!

Ian

**Comment by ianbjacobs** [comment]
Hi @rvm4,

I have updated the spec [1] and think that closes this issue.

Ian
[1] https://github.com/w3c/webpayments-methods-tokenization/commit/9de80077c6e2c4da31a8b50b5657dcfe89749c2a
