### ISSUE TITLE
Wording of tokens used

### ISSUE THREAD

**Issue by MasterKeyur** [w3c/webpayments-methods-tokenization#5]
Tokens issued before payment authorization:
_[kp] - we can call it **Token generated by physical card** as all tokens do require payment_ authorization in form of user offering the card or entering pin. 
Tokens stored in physical cards that are communicated via point of sale devices.
Tokens stored or generated in user devices and returned by native mobile payment apps.
Tokens issued after payment authorization
_[kp] - we can call it **Tokens issued by PSP to merchants**. Here also user performs authorization by sign in merchant portal. Just want to make sure authorization is not taken in a different meaning._ 
After the merchant (or their PSP) has collected user credentials, the credentials are stored in a secure vault and the merchant receives a token for subsequent business activities (e.g., customer tracking).

**Comment by ianbjacobs** [comment]
Thanks @masterkeyur, I have made edits based on your comments. Let me know if you are satisfied.

Ian

**Comment by ianbjacobs** [comment]
@MasterKeyur, in light of recent edits to the mission statement, are you satisfied with the text and can we close this issue?
https://github.com/w3c/webpayments-methods-tokenization/wiki
Ian

**Comment by ianbjacobs** [comment]
Closing for now given no further comment (and mission statement continues to evolve).
