### ISSUE TITLE
What happened to this spec?

### ISSUE THREAD

**Issue by rektide** [w3c/webpayments-methods-tokenization#55]
This spec appears abandoned? What happened? Is there any replacement? Will the web have a standard secure way for sites to accept credit card payment, without having to gain PCI compliance, or are we being abandoned to the credit card companies, left for them to develop their own payment handlers?

**Comment by ianbjacobs** [comment]
@rektide,

Work on this particular specification is on hold while we focus on an SRC payment method:
 https://github.com/w3c/src/wiki

It is possible that we will return to this as an independent module, but at the current time the group is looking at SRC as an umbrella payment method specification.

I am going to close this issue but happy to continue discussion.
