### ISSUE TITLE
Payment Method declaration may show duplicate card descriptions

### ISSUE THREAD

**Issue by oyiptong** [w3c/webpayments-methods-tokenization#9]
If a merchant specifies a payment method, say, using both `provider-tokenized-card` and `basic-card`, the user experience may be confusing to the user.

It would display the last four and the network logo twice.

Should the merchant bear the burden of choosing which payment handler to include?

**Comment by ianbjacobs** [comment]
Hi oyiptong,

I think this is a user experience issue for implementations of payment handler: what to do when two payment instruments with the same data are available in one or more payment apps? Can we move this issue to the payment handler issues list?

Ian

**Comment by ianbjacobs** [comment]
No action lately; closing for now.
